{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.name }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  rules:
    {{- range $host := .Values.ingress.hosts }}
    - host: {{ $host.host }}
      http:
        paths:
          {{- range $path := $host.paths }}
          - path: {{ $path.path | default "/" }}
            pathType: {{ $path.pathType | default "Prefix" }}
            backend:
              service:
                name: {{ $.Values.name }}
                port:
                  number: {{ $.Values.service.port }}
          {{- end }}
    {{- end }}
{{- end }}